<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Repositories\**" />
    <Content Remove="Repositories\**" />
    <EmbeddedResource Remove="Repositories\**" />
    <None Remove="Repositories\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\AircraftMaintenance\Views\AircraftDashboard\" />
    <Folder Include="Areas\Settings\Views\AircraftVersions\" />
    <Folder Include="Areas\Settings\Views\AircraftManufacturers\" />
    <Folder Include="Areas\Settings\Views\Home\" />
    <Folder Include="Controllers\AircraftMaintenance\" />
    <Folder Include="Controllers\HR\" />
    <Folder Include="Controllers\Medical\" />
    <Folder Include="Controllers\SquadronOps\" />
    <Folder Include="Views\Planning\SortieCrew\" />
    <Folder Include="Views\Planning\Sortie\" />
    <Folder Include="Views\Planning\ODV\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" Version="2.3.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
  </ItemGroup>

</Project>
