// <auto-generated />
using System;
using FRAProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FRAProject.Migrations
{
    [DbContext(typeof(FRAContext))]
    [Migration("20260422215244_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.AcCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AcCategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("AcCategories", "dbo");
                });

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.AcStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AcStatusTypes", "dbo");
                });

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcStatusTypeId")
                        .HasColumnType("int");

                    b.Property<int>("AcTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("BaseId")
                        .HasColumnType("int");

                    b.Property<string>("IntCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Obs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Serviceable")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TailNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcStatusTypeId");

                    b.HasIndex("AcTypeId");

                    b.HasIndex("BaseId");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.AircraftDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Revision")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntilUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("AircraftDocuments", "dbo");
                });

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.AircraftDocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AircraftDocumentTypes", "dbo");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Base", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 7)");

                    b.HasKey("Id");

                    b.ToTable("Bases");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PatrimonialStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.Property<string>("Speciality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.HasIndex("SubDepartmentId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullRank")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("RankTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RankTypeId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.RankType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RankTypes");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.SubDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("SubDepartments");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Wing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcMainGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("BaseId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WingLong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AcMainGroupId");

                    b.HasIndex("BaseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Wings");
                });

            modelBuilder.Entity("FRAProject.Areas.Medical.Models.MedicalBilan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BilanType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FollowUpDays")
                        .HasColumnType("int");

                    b.Property<int?>("FollowUpMonths")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedicalCheckId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCheckId");

                    b.ToTable("MedicalBilans");
                });

            modelBuilder.Entity("FRAProject.Areas.Medical.Models.MedicalCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CheckType")
                        .HasColumnType("int");

                    b.Property<bool>("CorrectionOptique")
                        .HasColumnType("bit")
                        .HasColumnName("C_Optique");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CrewMemberId")
                        .HasColumnType("int");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("DecisionText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Derogation")
                        .HasColumnType("bit");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<int>("DurationYears")
                        .HasColumnType("int");

                    b.Property<string>("LateCheckReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextVuDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Obesite")
                        .HasColumnType("bit")
                        .HasColumnName("OBESITE");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("MedicalChecks");
                });

            modelBuilder.Entity("FRAProject.Areas.Settings.Models.AcMainGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AcCategoryId");

                    b.HasIndex("BaseId");

                    b.ToTable("AcMainGroups", "dbo");
                });

            modelBuilder.Entity("FRAProject.Areas.Settings.Models.AcType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcMainGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("AircraftManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxEngines")
                        .HasColumnType("int");

                    b.Property<double>("MaxGrossweight")
                        .HasColumnType("float");

                    b.Property<int>("MaxPassengers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AcMainGroupId");

                    b.HasIndex("AircraftManufacturerId");

                    b.ToTable("AcTypes", "dbo");
                });

            modelBuilder.Entity("FRAProject.Areas.Settings.Models.AircraftManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AircraftManufacturers", "dbo");
                });

            modelBuilder.Entity("FRAProject.Areas.Settings.Models.AircraftVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AcTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Code", "AcTypeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_AircraftVersions_Code_AcType");

                    b.HasIndex("Name", "AcTypeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_AircraftVersions_Name_AcType");

                    b.ToTable("AircraftVersions", "dbo");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.CallSign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("SquadronId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.HasIndex("Code");

                    b.HasIndex("SquadronId");

                    b.ToTable("CallSigns");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.CrewMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowedToSign")
                        .HasColumnType("bit");

                    b.Property<string>("Captain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrewMemberType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PrimaryQualificationId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<int>("SquadronId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("PrimaryQualificationId");

                    b.HasIndex("SquadronId");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.CrewMemberQualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrewMemberId")
                        .HasColumnType("int");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QualificationId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId");

                    b.HasIndex("CrewMemberId", "QualificationId");

                    b.ToTable("CrewMemberQualifications");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.FlightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cycles")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal?>("FuelUsedKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("HobbsEnd")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("HobbsStart")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("LandingUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MissionSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortieId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TachEnd")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("TachStart")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("TakeOffUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("SortieId");

                    b.ToTable("FlightLogs");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SquadronId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.HasIndex("SquadronId");

                    b.ToTable("Missions", (string)null);
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QualificationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Sortie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("AircraftId")
                        .HasColumnType("int");

                    b.Property<double?>("AirframeCycles")
                        .HasColumnType("float");

                    b.Property<double?>("AirframeHours")
                        .HasColumnType("float");

                    b.Property<int?>("AppContacts")
                        .HasColumnType("int");

                    b.Property<int?>("Approachs")
                        .HasColumnType("int");

                    b.Property<int?>("BaseId")
                        .HasColumnType("int");

                    b.Property<bool?>("BrakeChuteUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Configuration")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Cycles")
                        .HasColumnType("int");

                    b.Property<double?>("DayHours")
                        .HasColumnType("float");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalizedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FuelQuantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("FuelUsedLiters")
                        .HasColumnType("decimal(12,2)");

                    b.Property<double?>("HobbsEnd")
                        .HasColumnType("float");

                    b.Property<double?>("HobbsStart")
                        .HasColumnType("float");

                    b.Property<double?>("HobbsUsed")
                        .HasColumnType("float");

                    b.Property<double?>("IFRHours")
                        .HasColumnType("float");

                    b.Property<double?>("InstActual")
                        .HasColumnType("float");

                    b.Property<double?>("InstSimulated")
                        .HasColumnType("float");

                    b.Property<int?>("Interceptions")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LandingTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Landings")
                        .HasColumnType("int");

                    b.Property<string>("Malfunctions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NightHours")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("OdvId")
                        .HasColumnType("int");

                    b.Property<int?>("RadarContacts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RealLandingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RealTOFF")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SortieCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SquadronReportNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TGOsLandings")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TOFF")
                        .HasColumnType("time");

                    b.Property<double?>("TachEnd")
                        .HasColumnType("float");

                    b.Property<double?>("TachStart")
                        .HasColumnType("float");

                    b.Property<double?>("TachUsed")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AcTypeId");

                    b.HasIndex("AircraftId")
                        .HasDatabaseName("IX_Sortie_AircraftId");

                    b.HasIndex("BaseId")
                        .HasDatabaseName("IX_Sortie_BaseId");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("OdvId")
                        .HasDatabaseName("IX_Sortie_OdvId");

                    b.HasIndex("OdvId", "IsCompleted")
                        .HasDatabaseName("IX_Sorties_Odv_Completed");

                    b.ToTable("Sorties", (string)null);
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.SortieCrew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CrewMemberId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Seat")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("SortieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrewMemberId");

                    b.HasIndex("SortieId");

                    b.ToTable("SortieCrews");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Squadron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CallSign")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CallSignShort")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FrenchName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("Squadrons");
                });

            modelBuilder.Entity("FRAProject.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AcMainGroupId")
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("BaseId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SquadronId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FRAProject.Models.MaintenanceComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCycles")
                        .HasColumnType("int");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("MaintenanceComponents");
                });

            modelBuilder.Entity("FRAProject.Models.MaintenanceThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastTriggeredUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Repeatable")
                        .HasColumnType("bit");

                    b.Property<string>("ThresholdType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("MaintenanceThresholds");
                });

            modelBuilder.Entity("FRAProject.Models.MaintenanceWorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThresholdId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TriggeredTotalCycles")
                        .HasColumnType("int");

                    b.Property<int>("TriggeredTotalMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ThresholdId");

                    b.ToTable("MaintenanceWorkOrders");
                });

            modelBuilder.Entity("FRAProject.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BaseId")
                        .HasColumnType("int");

                    b.Property<string>("Controller")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Roles")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "SortOrder");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("FRAProject.Models.Odv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcMainGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BaseId")
                        .HasColumnType("int");

                    b.Property<int>("CallSignId")
                        .HasColumnType("int")
                        .HasColumnName("CallSignId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPreflightApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<string>("MissionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Obs")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OdvDate")
                        .HasColumnType("date");

                    b.Property<string>("OdvStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<int>("SquadronId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TOFF")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AcMainGroupId");

                    b.HasIndex("BaseId");

                    b.HasIndex("CallSignId");

                    b.HasIndex("MissionId");

                    b.HasIndex("SquadronId", "OdvDate")
                        .IsUnique()
                        .HasDatabaseName("UX_Odv_Squadron_OdvDate");

                    b.ToTable("Odvs", (string)null);
                });

            modelBuilder.Entity("FRAProject.Models.UserDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDocuments");
                });

            modelBuilder.Entity("FRAProject.Models.UserQualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IssuedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserQualifications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.Aircraft", b =>
                {
                    b.HasOne("FRAProject.Areas.AircraftMaintenance.Models.AcStatusType", "AcStatusType")
                        .WithMany("Aircrafts")
                        .HasForeignKey("AcStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.Settings.Models.AcType", "AcType")
                        .WithMany("Aircrafts")
                        .HasForeignKey("AcTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.HR.Models.Base", null)
                        .WithMany("Aircraft")
                        .HasForeignKey("BaseId");

                    b.Navigation("AcStatusType");

                    b.Navigation("AcType");
                });

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.AircraftDocument", b =>
                {
                    b.HasOne("FRAProject.Areas.AircraftMaintenance.Models.Aircraft", "Aircraft")
                        .WithMany("Documents")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.AircraftMaintenance.Models.AircraftDocumentType", "DocumentType")
                        .WithMany("AircraftDocuments")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Department", b =>
                {
                    b.HasOne("FRAProject.Areas.HR.Models.Base", "Base")
                        .WithMany("Departments")
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Base");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Person", b =>
                {
                    b.HasOne("FRAProject.Areas.HR.Models.Rank", "Rank")
                        .WithMany("Persons")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.HR.Models.SubDepartment", "SubDepartment")
                        .WithMany("Persons")
                        .HasForeignKey("SubDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("SubDepartment");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Rank", b =>
                {
                    b.HasOne("FRAProject.Areas.HR.Models.RankType", "RankType")
                        .WithMany("Ranks")
                        .HasForeignKey("RankTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RankType");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.SubDepartment", b =>
                {
                    b.HasOne("FRAProject.Areas.HR.Models.Department", "Department")
                        .WithMany("SubDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Wing", b =>
                {
                    b.HasOne("FRAProject.Areas.Settings.Models.AcMainGroup", "AcMainGroup")
                        .WithMany()
                        .HasForeignKey("AcMainGroupId");

                    b.HasOne("FRAProject.Areas.HR.Models.Base", "Base")
                        .WithMany()
                        .HasForeignKey("BaseId");

                    b.HasOne("FRAProject.Areas.HR.Models.Department", "Department")
                        .WithMany("Wings")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcMainGroup");

                    b.Navigation("Base");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FRAProject.Areas.Medical.Models.MedicalBilan", b =>
                {
                    b.HasOne("FRAProject.Areas.Medical.Models.MedicalCheck", "MedicalCheck")
                        .WithMany("Bilans")
                        .HasForeignKey("MedicalCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCheck");
                });

            modelBuilder.Entity("FRAProject.Areas.Medical.Models.MedicalCheck", b =>
                {
                    b.HasOne("FRAProject.Areas.SquadronOps.Models.CrewMember", "CrewMember")
                        .WithMany("MedicalChecks")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewMember");
                });

            modelBuilder.Entity("FRAProject.Areas.Settings.Models.AcMainGroup", b =>
                {
                    b.HasOne("FRAProject.Areas.AircraftMaintenance.Models.AcCategory", "AcCategory")
                        .WithMany("AcMainGroups")
                        .HasForeignKey("AcCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.HR.Models.Base", "Base")
                        .WithMany("AcMainGroups")
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcCategory");

                    b.Navigation("Base");
                });

            modelBuilder.Entity("FRAProject.Areas.Settings.Models.AcType", b =>
                {
                    b.HasOne("FRAProject.Areas.Settings.Models.AcMainGroup", "AcMainGroup")
                        .WithMany("AcTypes")
                        .HasForeignKey("AcMainGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.Settings.Models.AircraftManufacturer", "AircraftManufacturer")
                        .WithMany()
                        .HasForeignKey("AircraftManufacturerId");

                    b.Navigation("AcMainGroup");

                    b.Navigation("AircraftManufacturer");
                });

            modelBuilder.Entity("FRAProject.Areas.Settings.Models.AircraftVersion", b =>
                {
                    b.HasOne("FRAProject.Areas.Settings.Models.AcType", "AcType")
                        .WithMany("AircraftVersions")
                        .HasForeignKey("AcTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AircraftVersions_AcType");

                    b.Navigation("AcType");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.CallSign", b =>
                {
                    b.HasOne("FRAProject.Areas.HR.Models.Base", "Base")
                        .WithMany()
                        .HasForeignKey("BaseId");

                    b.HasOne("FRAProject.Areas.SquadronOps.Models.Squadron", "Squadron")
                        .WithMany()
                        .HasForeignKey("SquadronId");

                    b.Navigation("Base");

                    b.Navigation("Squadron");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.CrewMember", b =>
                {
                    b.HasOne("FRAProject.Areas.HR.Models.Person", "Person")
                        .WithOne("CrewMember")
                        .HasForeignKey("FRAProject.Areas.SquadronOps.Models.CrewMember", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.SquadronOps.Models.Qualification", "PrimaryQualification")
                        .WithMany()
                        .HasForeignKey("PrimaryQualificationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FRAProject.Areas.SquadronOps.Models.Squadron", "Squadron")
                        .WithMany("CrewMembers")
                        .HasForeignKey("SquadronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("PrimaryQualification");

                    b.Navigation("Squadron");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.CrewMemberQualification", b =>
                {
                    b.HasOne("FRAProject.Areas.SquadronOps.Models.CrewMember", "CrewMember")
                        .WithMany("CrewMemberQualifications")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.SquadronOps.Models.Qualification", "Qualification")
                        .WithMany("CrewMemberQualifications")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CrewMember");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.FlightLog", b =>
                {
                    b.HasOne("FRAProject.Areas.AircraftMaintenance.Models.Aircraft", "Aircraft")
                        .WithMany("FlightLogs")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.SquadronOps.Models.Sortie", "Sortie")
                        .WithOne()
                        .HasForeignKey("FRAProject.Areas.SquadronOps.Models.FlightLog", "SortieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Sortie");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Mission", b =>
                {
                    b.HasOne("FRAProject.Areas.SquadronOps.Models.Phase", "Phase")
                        .WithMany("Missions")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.SquadronOps.Models.Squadron", "Squadron")
                        .WithMany("Missions")
                        .HasForeignKey("SquadronId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Phase");

                    b.Navigation("Squadron");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Sortie", b =>
                {
                    b.HasOne("FRAProject.Areas.Settings.Models.AcType", "AcType")
                        .WithMany("Sorties")
                        .HasForeignKey("AcTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.AircraftMaintenance.Models.Aircraft", "Aircraft")
                        .WithMany("Sorties")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FRAProject.Models.Odv", "Odv")
                        .WithMany("Sorties")
                        .HasForeignKey("OdvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcType");

                    b.Navigation("Aircraft");

                    b.Navigation("Odv");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.SortieCrew", b =>
                {
                    b.HasOne("FRAProject.Areas.SquadronOps.Models.CrewMember", "CrewMember")
                        .WithMany()
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.SquadronOps.Models.Sortie", "Sortie")
                        .WithMany("SortieCrews")
                        .HasForeignKey("SortieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewMember");

                    b.Navigation("Sortie");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Squadron", b =>
                {
                    b.HasOne("FRAProject.Areas.HR.Models.Wing", "Wing")
                        .WithMany("Squadrons")
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("FRAProject.Models.MaintenanceComponent", b =>
                {
                    b.HasOne("FRAProject.Areas.AircraftMaintenance.Models.Aircraft", "Aircraft")
                        .WithMany("Components")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("FRAProject.Models.MaintenanceThreshold", b =>
                {
                    b.HasOne("FRAProject.Models.MaintenanceComponent", "Component")
                        .WithMany("Thresholds")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("FRAProject.Models.MaintenanceWorkOrder", b =>
                {
                    b.HasOne("FRAProject.Areas.AircraftMaintenance.Models.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FRAProject.Models.MaintenanceComponent", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FRAProject.Models.MaintenanceThreshold", "Threshold")
                        .WithMany()
                        .HasForeignKey("ThresholdId");

                    b.Navigation("Aircraft");

                    b.Navigation("Component");

                    b.Navigation("Threshold");
                });

            modelBuilder.Entity("FRAProject.Models.Odv", b =>
                {
                    b.HasOne("FRAProject.Areas.Settings.Models.AcMainGroup", "AcMainGroup")
                        .WithMany("Odvs")
                        .HasForeignKey("AcMainGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.HR.Models.Base", "Base")
                        .WithMany()
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FRAProject.Areas.SquadronOps.Models.CallSign", "CallSign")
                        .WithMany()
                        .HasForeignKey("CallSignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.SquadronOps.Models.Mission", "Mission")
                        .WithMany("Odvs")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FRAProject.Areas.SquadronOps.Models.Squadron", "Squadron")
                        .WithMany("Odvs")
                        .HasForeignKey("SquadronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcMainGroup");

                    b.Navigation("Base");

                    b.Navigation("CallSign");

                    b.Navigation("Mission");

                    b.Navigation("Squadron");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FRAProject.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FRAProject.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FRAProject.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FRAProject.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.AcCategory", b =>
                {
                    b.Navigation("AcMainGroups");
                });

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.AcStatusType", b =>
                {
                    b.Navigation("Aircrafts");
                });

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.Aircraft", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Documents");

                    b.Navigation("FlightLogs");

                    b.Navigation("Sorties");
                });

            modelBuilder.Entity("FRAProject.Areas.AircraftMaintenance.Models.AircraftDocumentType", b =>
                {
                    b.Navigation("AircraftDocuments");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Base", b =>
                {
                    b.Navigation("AcMainGroups");

                    b.Navigation("Aircraft");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Department", b =>
                {
                    b.Navigation("SubDepartments");

                    b.Navigation("Wings");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Person", b =>
                {
                    b.Navigation("CrewMember");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Rank", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.RankType", b =>
                {
                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.SubDepartment", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("FRAProject.Areas.HR.Models.Wing", b =>
                {
                    b.Navigation("Squadrons");
                });

            modelBuilder.Entity("FRAProject.Areas.Medical.Models.MedicalCheck", b =>
                {
                    b.Navigation("Bilans");
                });

            modelBuilder.Entity("FRAProject.Areas.Settings.Models.AcMainGroup", b =>
                {
                    b.Navigation("AcTypes");

                    b.Navigation("Odvs");
                });

            modelBuilder.Entity("FRAProject.Areas.Settings.Models.AcType", b =>
                {
                    b.Navigation("AircraftVersions");

                    b.Navigation("Aircrafts");

                    b.Navigation("Sorties");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.CrewMember", b =>
                {
                    b.Navigation("CrewMemberQualifications");

                    b.Navigation("MedicalChecks");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Mission", b =>
                {
                    b.Navigation("Odvs");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Phase", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Qualification", b =>
                {
                    b.Navigation("CrewMemberQualifications");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Sortie", b =>
                {
                    b.Navigation("SortieCrews");
                });

            modelBuilder.Entity("FRAProject.Areas.SquadronOps.Models.Squadron", b =>
                {
                    b.Navigation("CrewMembers");

                    b.Navigation("Missions");

                    b.Navigation("Odvs");
                });

            modelBuilder.Entity("FRAProject.Models.MaintenanceComponent", b =>
                {
                    b.Navigation("Thresholds");
                });

            modelBuilder.Entity("FRAProject.Models.Odv", b =>
                {
                    b.Navigation("Sorties");
                });
#pragma warning restore 612, 618
        }
    }
}
